Prompt Package PKG_CONTEXT_API;
--
-- PKG_CONTEXT_API  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--   STANDARD (Package)
--   DBMS_SESSION (Synonym)
--
CREATE OR REPLACE PACKAGE &TRANSFORMPV_USER..PKG_CONTEXT_API
AS
   GV_CONTEXT   VARCHAR2 (100) := 'E2BR2R3_CONTEXT';

   PROCEDURE P_SET_PARAMETER (P_NAME IN VARCHAR2, P_VALUE IN VARCHAR2);

   FUNCTION F_GET_PARAMETER (P_NAME IN VARCHAR2)
      RETURN VARCHAR2;

   PROCEDURE CLEAR_ALL_CONTEXT;
END PKG_CONTEXT_API;
/


