PROMPT View VW_AGENCY_DIFF;
--
-- VW_AGENCY_DIFF  (View) 
--
--  Dependencies: 
--   LM_REGULATORY_CONTACT (Table)
--   E2B_LM_REGULATORY_CONTACT (Synonym)
--
CREATE OR REPLACE VIEW &TRANSFORMPV_USER..VW_AGENCY_DIFF (AGENCY_ID,
                                             AGENCY_NAME,
                                             REG_NUM,
                                             CONTACT_NAME,
                                             TITLE,
                                             ADDRESS,
                                             CITY,
                                             STATE,
                                             POST_CODE,
                                             COUNTRY,
                                             PHONE,
                                             FAX,
                                             EMAIL,
                                             OFF_LINE,
                                             PREF_METHOD,
                                             DEPARTMENT,
                                             FIRST_NAME,
                                             MIDDLE_NAME,
                                             TEL_EXT,
                                             TEL_CONT_CODE,
                                             FAX_EXT,
                                             FAX_CONT_CODE,
                                             MAX_E2B_RPT,
                                             VIEW_PRINT_METHOD,
                                             RECEIVER_TYPE,
                                             SENDER_TYPE,
                                             CONT_COUNTRY_ID,
                                             CONT_COMPANY_NAME,
                                             CONT_NAME,
                                             CONT_TITLE,
                                             CONT_ADDRESS,
                                             CONT_CITY,
                                             CONT_STATE,
                                             CONT_POSTCODE,
                                             CONT_PHONE,
                                             CONT_FAX,
                                             CONT_DEPARTMENT,
                                             CONT_FIRST_NAME,
                                             CONT_MIDDLE_NAME,
                                             CONT_TEL_EXT,
                                             CONT_TEL_CONT_CODE,
                                             CONT_FAX_EXT,
                                             CONT_FAX_CONT_CODE,
                                             SENDER_EMAIL,
                                             FAX_MAIN,
                                             TERM_SELECTION,
                                             FAX_COVER,
                                             RULE_MARKETED,
                                             RULE_INVESTIGATIONAL,
                                             REPORTS_PER_EMAIL,
                                             SINGLE_ATTACHMENT,
                                             EMAIL_BODY_TYPE,
                                             DELETED,
                                             CONT_LAB_CODE,
                                             CONTACT_TYPE,
                                             AWARE_SELECTION_ID,
                                             SUSAR_REPORTING,
                                             SMTP_FROM_EMAIL,
                                             SMTP_CC_EMAIL,
                                             SMTP_BCC_EMAIL,
                                             SMTP_READ_RECEIPT_FLAG,
                                             SMTP_DELIVERY_RECEIPT_FLAG,
                                             AUTO_ACCEPT_ICSR,
                                             TRANSMIT_E2B_ATTACHMENT,
                                             SUPPRESS_DUPLICATE_REPORTS,
                                             SUPPRESS_LICENSE_TYPE,
                                             AUTO_ACCEPT_ICSR_TYPE,
                                             AGENCY_NAME_J,
                                             CONT_COMPANY_NAME_J,
                                             USE_JPN_AWARE_DATE,
                                             MULT_RPT_MKT_DRUGS,
                                             MULT_RPT_INVEST_DRUGS,
                                             ADJUST_DUE_DT_FOR_HOLIDAYS,
                                             ENTERPRISE_ID,
                                             FAX_HEADER_J
                                            )
AS
   SELECT L.AGENCY_ID, L.AGENCY_NAME, L.REG_NUM, L.CONTACT_NAME, L.TITLE,
          L.ADDRESS, L.CITY, L.STATE, L.POST_CODE, L.COUNTRY, L.PHONE, L.FAX,
          L.EMAIL, L.OFF_LINE, L.PREF_METHOD, L.DEPARTMENT, L.FIRST_NAME,
          L.MIDDLE_NAME, L.TEL_EXT, L.TEL_CONT_CODE, L.FAX_EXT,
          L.FAX_CONT_CODE, L.MAX_E2B_RPT, L.VIEW_PRINT_METHOD,
          L.RECEIVER_TYPE, L.SENDER_TYPE, L.CONT_COUNTRY_ID,
          L.CONT_COMPANY_NAME, L.CONT_NAME, L.CONT_TITLE, L.CONT_ADDRESS,
          L.CONT_CITY, L.CONT_STATE, L.CONT_POSTCODE, L.CONT_PHONE,
          L.CONT_FAX, L.CONT_DEPARTMENT, L.CONT_FIRST_NAME,
          L.CONT_MIDDLE_NAME, L.CONT_TEL_EXT, L.CONT_TEL_CONT_CODE,
          L.CONT_FAX_EXT, L.CONT_FAX_CONT_CODE, L.SENDER_EMAIL, L.FAX_MAIN,
          L.TERM_SELECTION, L.FAX_COVER, L.RULE_MARKETED,
          L.RULE_INVESTIGATIONAL, L.REPORTS_PER_EMAIL, L.SINGLE_ATTACHMENT,
          L.EMAIL_BODY_TYPE, L.DELETED, L.CONT_LAB_CODE, L.CONTACT_TYPE,
          L.AWARE_SELECTION_ID, L.SUSAR_REPORTING, L.SMTP_FROM_EMAIL,
          L.SMTP_CC_EMAIL, L.SMTP_BCC_EMAIL, L.SMTP_READ_RECEIPT_FLAG,
          L.SMTP_DELIVERY_RECEIPT_FLAG, L.AUTO_ACCEPT_ICSR,
          L.TRANSMIT_E2B_ATTACHMENT, L.SUPPRESS_DUPLICATE_REPORTS,
          L.SUPPRESS_LICENSE_TYPE, L.AUTO_ACCEPT_ICSR_TYPE, L.AGENCY_NAME_J,
          L.CONT_COMPANY_NAME_J, L.USE_JPN_AWARE_DATE, L.MULT_RPT_MKT_DRUGS,
          L.MULT_RPT_INVEST_DRUGS, L.ADJUST_DUE_DT_FOR_HOLIDAYS,
          L.ENTERPRISE_ID, L.FAX_HEADER_J
     FROM &ARGUS_APP_USER..LM_REGULATORY_CONTACT L
   MINUS
   SELECT L.AGENCY_ID, L.AGENCY_NAME, L.REG_NUM, L.CONTACT_NAME, L.TITLE,
          L.ADDRESS, L.CITY, L.STATE, L.POST_CODE, L.COUNTRY, L.PHONE, L.FAX,
          L.EMAIL, L.OFF_LINE, L.PREF_METHOD, L.DEPARTMENT, L.FIRST_NAME,
          L.MIDDLE_NAME, L.TEL_EXT, L.TEL_CONT_CODE, L.FAX_EXT,
          L.FAX_CONT_CODE, L.MAX_E2B_RPT, L.VIEW_PRINT_METHOD,
          L.RECEIVER_TYPE, L.SENDER_TYPE, L.CONT_COUNTRY_ID,
          L.CONT_COMPANY_NAME, L.CONT_NAME, L.CONT_TITLE, L.CONT_ADDRESS,
          L.CONT_CITY, L.CONT_STATE, L.CONT_POSTCODE, L.CONT_PHONE,
          L.CONT_FAX, L.CONT_DEPARTMENT, L.CONT_FIRST_NAME,
          L.CONT_MIDDLE_NAME, L.CONT_TEL_EXT, L.CONT_TEL_CONT_CODE,
          L.CONT_FAX_EXT, L.CONT_FAX_CONT_CODE, L.SENDER_EMAIL, L.FAX_MAIN,
          L.TERM_SELECTION, L.FAX_COVER, L.RULE_MARKETED,
          L.RULE_INVESTIGATIONAL, L.REPORTS_PER_EMAIL, L.SINGLE_ATTACHMENT,
          L.EMAIL_BODY_TYPE, L.DELETED, L.CONT_LAB_CODE, L.CONTACT_TYPE,
          L.AWARE_SELECTION_ID, L.SUSAR_REPORTING, L.SMTP_FROM_EMAIL,
          L.SMTP_CC_EMAIL, L.SMTP_BCC_EMAIL, L.SMTP_READ_RECEIPT_FLAG,
          L.SMTP_DELIVERY_RECEIPT_FLAG, L.AUTO_ACCEPT_ICSR,
          L.TRANSMIT_E2B_ATTACHMENT, L.SUPPRESS_DUPLICATE_REPORTS,
          L.SUPPRESS_LICENSE_TYPE, L.AUTO_ACCEPT_ICSR_TYPE, L.AGENCY_NAME_J,
          L.CONT_COMPANY_NAME_J, L.USE_JPN_AWARE_DATE, L.MULT_RPT_MKT_DRUGS,
          L.MULT_RPT_INVEST_DRUGS, L.ADJUST_DUE_DT_FOR_HOLIDAYS,
          L.ENTERPRISE_ID, L.FAX_HEADER_J
     FROM E2B_LM_REGULATORY_CONTACT L
/


