CREATE TABLE &TRANSFORMPV_USER..E2B_R3VIEW_STATUS
(
  MESSAGE_NUMBER       VARCHAR2(500 CHAR),
  SAFETY_REPORT_ID     VARCHAR2(500 CHAR),
  R3_FILE_NAME         VARCHAR2(500 CHAR),
  LOGIN_USER_ID        NUMBER,
  LOGIN_USER_NAME      VARCHAR2(500 CHAR),
  ACCEPT_REJECT_FLAG   NUMBER,
  ACCEPT_REJECT_NOTES  VARCHAR2(3000 CHAR),
  R3_BATCH_NAME        VARCHAR2(500 CHAR),
  REPORT_TYPE          VARCHAR2(100 CHAR),
  MSGN_SAFETYID_FNAME  VARCHAR2(500 CHAR),
  DELETED              NUMBER,
  DELETED_DATE         DATE,
  INSERT_DATE          DATE
);

ALTER TABLE &TRANSFORMPV_USER..E2B_R3VIEW_STATUS ADD (
  CONSTRAINT PK_R3VIEW_STATUS
  PRIMARY KEY
  (MESSAGE_NUMBER, SAFETY_REPORT_ID, R3_FILE_NAME));
  
GRANT SELECT ON &TRANSFORMPV_USER..E2B_R3VIEW_STATUS TO SELECT_ANY_PVTRANSFORM;  
GRANT SELECT,INSERT,UPDATE,DELETE ON &TRANSFORMPV_USER..E2B_R3VIEW_STATUS TO UPDATE_ANY_PVTRANSFORM;
