ALTER TABLE &TRANSFORMPV_USER..E2B_IMPORT_QUEUE
ADD FILE_NAME_ATTACH VARCHAR2(3000 CHAR);

ALTER TABLE &TRANSFORMPV_USER..E2B_IMPORT_QUEUE
ADD FILE_CONTENT_ATTACH BLOB;

ALTER TABLE &TRANSFORMPV_USER..E2B_IMPORT_QUEUE
ADD FILE_ATTACH_CLASSIFICATION NUMBER;

ALTER TABLE &TRANSFORMPV_USER..E2B_IMPORT_QUEUE
ADD MESSAGE_NUMBER VARCHAR2(200 CHAR);

ALTER TABLE &TRANSFORMPV_USER..E2B_IMPORT_QUEUE
DROP COLUMN IMPORT_R3XMLFILENAME;

ALTER TABLE &TRANSFORMPV_USER..E2B_IMPORT_QUEUE
DROP COLUMN FILE_CONTENT_R3XML;

ALTER TABLE &TRANSFORMPV_USER..E2B_IMPORT_QUEUE
DROP COLUMN IMPORT_R2R3PDFFILENAME;

ALTER TABLE &TRANSFORMPV_USER..E2B_IMPORT_QUEUE
DROP COLUMN FILE_CONTENT_R2R3PDF;

ALTER TABLE &TRANSFORMPV_USER..E2B_IMPORT_QUEUE
ADD DESCRIPTION VARCHAR2(200 CHAR);