ALTER TABLE &TRANSFORMPV_USER..E2B_IMPORT_QUEUE ADD (CONSTRAINT E2B_IMPORT_QUEUE_PK PRIMARY KEY(ID));
CREATE INDEX &TRANSFORMPV_USER..I_E2B_IMPORT_QUEUE_SAFETY_MSG ON &TRANSFORMPV_USER..E2B_IMPORT_QUEUE(SAFETYREPORTID,MESSAGE_NUMBER);

