Prompt Create TransformPV Roles;

CREATE ROLE SELECT_ANY_PVTRANSFORM NOT IDENTIFIED
/
CREATE ROLE UPDATE_ANY_PVTRANSFORM NOT IDENTIFIED
/
BEGIN
FOR C2 IN (SELECT OBJECT_NAME FROM ALL_OBJECTS AO WHERE upper(OWNER) = upper('&TRANSFORMPV_USER.')  AND OBJECT_TYPE IN('TABLE','VIEWS') )
LOOP
EXECUTE IMMEDIATE 'GRANT SELECT ON &TRANSFORMPV_USER..' ||C2.OBJECT_NAME || ' TO SELECT_ANY_PVTRANSFORM';
END LOOP;
END;
/
BEGIN
FOR C2 IN (SELECT OBJECT_NAME,OBJECT_TYPE FROM ALL_OBJECTS AO WHERE upper(OWNER) = upper('&TRANSFORMPV_USER.')  AND OBJECT_TYPE IN ('PROCEDURE','FUNCTION','PACKAGE','TABLE'))
LOOP
IF C2.OBJECT_TYPE = 'TABLE' THEN
EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON &TRANSFORMPV_USER..' ||C2.OBJECT_NAME || ' TO UPDATE_ANY_PVTRANSFORM';
ELSE
EXECUTE IMMEDIATE 'GRANT EXECUTE ON &TRANSFORMPV_USER..' ||C2.OBJECT_NAME || ' TO UPDATE_ANY_PVTRANSFORM';
END IF;
END LOOP;
END;
/
--GRANT SELECT_ANY_PVTRANSFORM TO ARGUS_APP_SUPPORT_SEL
--/
--GRANT UPDATE_ANY_PVTRANSFORM TO ARGUS_APP_SUPPORT_UPD
--/