GRANT INSERT ON &TRANSFORMPV_USER..SAFETYREPORT_R3VIEW TO &ESM_OWNER_USER
/
GRANT SELECT ON &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY TO &ARGUS_APP_USER
/
GRANT SELECT ON &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY TO &ARGUS_ROLE
/
--GRANT SELECT ON &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY TO ARGUS_LOGIN
--GRANT SELECT ON &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY TO ARGUS_LOGIN_I
--GRANT SELECT ON &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY TO ARGUS_LOGIN_IPS
GRANT CREATE ROLE TO &TRANSFORMPV_USER.
/
