Prompt Table E2B_LDAP_SERVERS_HIST;
--
-- E2B_LDAP_SERVERS_HIST  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..E2B_LDAP_SERVERS_HIST
(
  SERVER_ID             NUMBER(22),
  SERVER_ALIAS          VARCHAR2(1020 CHAR),
  SERVER_NAME           VARCHAR2(1020 CHAR),
  SERVER_PORT           NUMBER(22),
  BASE_DN               VARCHAR2(1020 CHAR),
  TIME_OUT_SEC          NUMBER(22),
  SEARCH_USER_DN        VARCHAR2(1020 CHAR),
  SEARCH_PASSWORD       VARCHAR2(1020 CHAR),
  SEARCH_KEY            VARCHAR2(1020 CHAR),
  SSL                   NUMBER(22),
  ANONYMOUS             NUMBER(22),
  DELETED               NUMBER(22),
  CREATED_DATE          DATE,
  CREATED_BY            NUMBER(22),
  MODIFIED_DATE         DATE,
  MODIFIED_BY           NUMBER(22),
  DUP_CHECK_NAME        VARCHAR2(500 CHAR),
  VERSION_NUMBER        NUMBER,
  AUDIT_ID              NUMBER,
  OPERATION_TYPE        NUMBER,
  EFFECTIVE_START_DATE  DATE,
  EFFECTIVE_END_DATE    DATE,
  CURRENT_FLG           NUMBER,
  INSERT_DATE           DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/
