Prompt Table E2B_CFG_COLOR_MAP_HIST;
--
-- E2B_CFG_COLOR_MAP_HIST  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..E2B_CFG_COLOR_MAP_HIST
(
  COLOR_ID              NUMBER(22),
  MISSING_IN_R2         VARCHAR2(40 CHAR),
  MISSING_IN_R3         VARCHAR2(40 CHAR),
  NO_MAPPING            VARCHAR2(40 CHAR),
  DELETED               NUMBER(22),
  CREATED_BY            NUMBER(22),
  CREATED_DATE          DATE,
  MODIFIED_BY           NUMBER(22),
  MODIFIED_DATE         DATE,
  COLOR_CONFIG          VARCHAR2(100 CHAR),
  VERSION_NUMBER        NUMBER,
  AUDIT_ID              NUMBER,
  OPERATION_TYPE        NUMBER,
  EFFECTIVE_START_DATE  DATE,
  EFFECTIVE_END_DATE    DATE,
  CURRENT_FLG           NUMBER,
  INSERT_DATE           DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/
