Prompt Table E2B_CMN_FLAG_LOOKUP;
--
-- E2B_CMN_FLAG_LOOKUP  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..E2B_CMN_FLAG_LOOKUP
(
  ID          VARCHAR2(10 CHAR),
  FLAGVALUE1  VARCHAR2(10 CHAR),
  DELETED     NUMBER                            DEFAULT 0,
  FLAGVALUE2  VARCHAR2(100 CHAR),
  FLAGVALUE3  VARCHAR2(100 CHAR),
  FLAGVALUE4  VARCHAR2(100 CHAR),
  FLAGVALUE5  VARCHAR2(500 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

CREATE UNIQUE INDEX &TRANSFORMPV_USER..E2B_CMN_FLAG_LOOKUP_PK ON &TRANSFORMPV_USER..E2B_CMN_FLAG_LOOKUP
(ID)
LOGGING
NOPARALLEL
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CMN_FLAG_LOOKUP
 ADD CONSTRAINT E2B_CMN_FLAG_LOOKUP_PK
 PRIMARY KEY
 (ID)
 /
 
