Prompt Table E2B_R3_CFG_AGENCY;
--
-- E2B_R3_CFG_AGENCY  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY
(
  AGENCY_ID             NUMBER,
  AGENCY_NAME           VARCHAR2(200 CHAR),
  UPGRADE_XSL           VARCHAR2(1000 CHAR),
  DOWNGRADE_XSL         VARCHAR2(1000 CHAR),
  ACK_UPGRADE_XSL       VARCHAR2(1000 CHAR),
  ACK_DOWNGRADE_XSL     VARCHAR2(1000 CHAR),
  UPGRADE_IN_FOLDER     VARCHAR2(1000 CHAR),
  UPGRADE_OUT_FOLDER    VARCHAR2(1000 CHAR),
  DOWNGRADE_IN_FOLDER   VARCHAR2(1000 CHAR),
  DOWNGRADE_OUT_FOLDER  VARCHAR2(1000 CHAR),
  BINARY_FOLDER         VARCHAR2(1000 CHAR),
  CREATED_BY            NUMBER,
  CREATED_DATE          DATE,
  MODIFIED_BY           NUMBER,
  MODIFIED_DATE         DATE,
  DELETED               NUMBER,
  DELETED_DATE          DATE,
  DRAFT_E2B_CLASS_ID    NUMBER,
  DRAFT_HTML_CLASS_ID   NUMBER,
  FINAL_E2B_CLASS_ID    NUMBER,
  FINAL_HTML_CLASS_ID   NUMBER,
  E2B_PROFILE_ID        NUMBER,
  ACK_PROFILE_ID        NUMBER,
  XSD_FILE              VARCHAR2(500 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY
 ADD CONSTRAINT E2B_R3_CFG_AGENCY_PK
 PRIMARY KEY
 (AGENCY_ID)
 /

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY
ADD (ENABLED NUMBER DEFAULT 1);

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY
ADD (ALLOW_MULTI_ACK NUMBER DEFAULT 0);


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY
MODIFY(AGENCY_NAME VARCHAR2(200 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY
MODIFY(UPGRADE_XSL VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY
MODIFY(DOWNGRADE_XSL VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY
MODIFY(ACK_UPGRADE_XSL VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY
MODIFY(ACK_DOWNGRADE_XSL VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY
MODIFY(UPGRADE_IN_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY
MODIFY(UPGRADE_OUT_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY
MODIFY(DOWNGRADE_IN_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY
MODIFY(DOWNGRADE_OUT_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY
MODIFY(BINARY_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY
MODIFY(XSD_FILE VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY
 ADD (CURRENT_VERSION  NUMBER)
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY
 ADD (EXP_ATTACHMENT_PATH  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY
 ADD (IMP_ATTACHMENT_PATH  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY
 ADD (IMP_ATTACHMENT_CLASS_ID  NUMBER)
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY
 ADD (FINAL_FILE_FORMAT  VARCHAR2(100 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY DROP COLUMN BINARY_FOLDER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY DROP COLUMN DRAFT_E2B_CLASS_ID
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY DROP COLUMN DRAFT_HTML_CLASS_ID
/
