Prompt Table E2B_IMPORT_QUEUE;

CREATE TABLE &TRANSFORMPV_USER..E2B_IMPORT_QUEUE
(
  ID                      NUMBER,
  MSG_TYPE                VARCHAR2(100 CHAR),
  MSG_TYPE_ID             NUMBER,
  SAFETYREPORTID          VARCHAR2(200 CHAR),
  IMPORT_R3XMLFILENAME    VARCHAR2(200 CHAR),
  FILE_CONTENT_R3XML      BLOB,
  IMPORT_R2R3PDFFILENAME  VARCHAR2(200 CHAR),
  FILE_CONTENT_R2R3PDF    BLOB,
  AGENCY_ID               NUMBER,
  STATUS                  NUMBER,
  STATUS_MSG              VARCHAR2(3000 CHAR),
  DATE_INSERT             DATE,
  DATE_PROCESSED          DATE,
  NO_OF_TRIES             NUMBER,
  LAST_TRIED_TIME         DATE
)
/
