Prompt Table E2B_CFG_COLOR_MAP;
--
-- E2B_CFG_COLOR_MAP  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..E2B_CFG_COLOR_MAP
(
  COLOR_ID       NUMBER,
  MISSING_IN_R2  VARCHAR2(10 CHAR),
  MISSING_IN_R3  VARCHAR2(10 CHAR),
  NO_MAPPING     VARCHAR2(10 CHAR),
  DELETED        NUMBER                         DEFAULT 0,
  CREATED_BY     NUMBER,
  CREATED_DATE   DATE,
  MODIFIED_BY    NUMBER,
  MODIFIED_DATE  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/
ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_COLOR_MAP
 ADD CONSTRAINT E2B_CFG_COLOR_MAP_PK
 PRIMARY KEY
 (COLOR_ID)
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_COLOR_MAP
 ADD (COLOR_CONFIG  VARCHAR2(100 CHAR))
 /

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_COLOR_MAP
 ADD (CURRENT_VERSION  NUMBER)
 /
