Prompt Table E2B_R3_CFG_SYSTEM_HIST;
--
-- E2B_R3_CFG_SYSTEM_HIST  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
(
  O_APPLICATION         VARCHAR2(200 CHAR),
  O_BFC_IN_FOLDER       VARCHAR2(1000 CHAR),
  O_BFC_OUT_FOLDER      VARCHAR2(1000 CHAR),
  O_BFC_BKP_FOLDER      VARCHAR2(1000 CHAR),
  O_ERROR_FOLDER        VARCHAR2(1000 CHAR),
  O_LOG_FOLDER          VARCHAR2(1000 CHAR),
  O_ACK_IDENTIFIER      VARCHAR2(200 CHAR),
  O_CREATED_BY          NUMBER,
  O_CREATED_DATE        DATE,
  O_MODIFIED_BY         NUMBER,
  O_MODIFIED_DATE       DATE,
  O_DELETED             NUMBER                  DEFAULT 0,
  O_DELETED_DATE        DATE,
  N_APPLICATION         VARCHAR2(200 CHAR),
  N_BFC_IN_FOLDER       VARCHAR2(1000 CHAR),
  N_BFC_OUT_FOLDER      VARCHAR2(1000 CHAR),
  N_BFC_BKP_FOLDER      VARCHAR2(1000 CHAR),
  N_ERROR_FOLDER        VARCHAR2(1000 CHAR),
  N_LOG_FOLDER          VARCHAR2(1000 CHAR),
  N_ACK_IDENTIFIER      VARCHAR2(200 CHAR),
  N_CREATED_BY          NUMBER,
  N_CREATED_DATE        DATE,
  N_MODIFIED_BY         NUMBER,
  N_MODIFIED_DATE       DATE,
  N_DELETED             NUMBER                  DEFAULT 0,
  N_DELETED_DATE        DATE,
  VERSION_NUMBER        NUMBER,
  AUDIT_ID              NUMBER,
  OPERATION_TYPE        VARCHAR2(10 CHAR),
  EFFECTIVE_START_DATE  DATE,
  EFFECTIVE_END_DATE    DATE,
  CURRENT_FLG           NUMBER,
  INSERT_DATE           DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST ADD(O_HTML_FOLDER VARCHAR2(500), O_PDF_TEMPLATE_FOLDER VARCHAR2(500), N_HTML_FOLDER VARCHAR2(500), N_PDF_TEMPLATE_FOLDER VARCHAR2(500))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
MODIFY(O_APPLICATION VARCHAR2(200 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
MODIFY(O_BFC_IN_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
MODIFY(O_BFC_OUT_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
MODIFY(O_BFC_BKP_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
MODIFY(O_ERROR_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
MODIFY(O_LOG_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
MODIFY(O_ACK_IDENTIFIER VARCHAR2(200 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
MODIFY(N_APPLICATION VARCHAR2(200 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
MODIFY(N_BFC_IN_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
MODIFY(N_BFC_OUT_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
MODIFY(N_BFC_BKP_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
MODIFY(N_ERROR_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
MODIFY(N_LOG_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
MODIFY(N_ACK_IDENTIFIER VARCHAR2(200 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
MODIFY(OPERATION_TYPE VARCHAR2(10 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
MODIFY(O_HTML_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
MODIFY(O_PDF_TEMPLATE_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
MODIFY(N_HTML_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
MODIFY(N_PDF_TEMPLATE_FOLDER VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM
 ADD (APPLICATION_ID  NUMBER)
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM
 ADD (CURRENT_VERSION  NUMBER)
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM
 ADD (BINARY_FOLDER  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
 ADD (APPLICATION  VARCHAR2(800 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
 ADD (BFC_IN_FOLDER  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
 ADD (BFC_OUT_FOLDER  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
 ADD (BFC_BKP_FOLDER  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
 ADD (ERROR_FOLDER  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
 ADD (LOG_FOLDER  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
 ADD (ACK_IDENTIFIER  VARCHAR2(800 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
 ADD (CREATED_BY  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
 ADD (CREATED_DATE  DATE)
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
 ADD (MODIFIED_BY  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
 ADD (MODIFIFED_DATE  DATE)
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
 ADD (DELETED  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
 ADD (DELETED_DATE  DATE)
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
 ADD (HTML_FOLDER  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
 ADD (PDF_TEMPLATE_FOLDER  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
 ADD (APPLICATION_ID  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
MODIFY(OPERATION_TYPE NUMBER)
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST
 ADD (BINARY_FOLDER  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN O_APPLICATION
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN O_BFC_IN_FOLDER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN O_BFC_OUT_FOLDER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN O_BFC_BKP_FOLDER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN O_ERROR_FOLDER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN O_LOG_FOLDER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN O_ACK_IDENTIFIER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN O_CREATED_BY
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN O_CREATED_DATE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN O_MODIFIED_BY
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN O_MODIFIED_DATE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN O_DELETED
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN O_DELETED_DATE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN N_APPLICATION
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN N_BFC_IN_FOLDER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN N_BFC_OUT_FOLDER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN N_BFC_BKP_FOLDER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN N_ERROR_FOLDER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN N_LOG_FOLDER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN N_ACK_IDENTIFIER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN N_CREATED_BY
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN N_CREATED_DATE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN N_MODIFIED_BY
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN N_MODIFIED_DATE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN N_DELETED
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN N_DELETED_DATE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN O_HTML_FOLDER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN O_PDF_TEMPLATE_FOLDER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN N_HTML_FOLDER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM_HIST DROP COLUMN N_PDF_TEMPLATE_FOLDER
/
