Prompt Table E2B_TRANSFORM_STATUS;
--
-- E2B_TRANSFORM_STATUS  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..E2B_TRANSFORM_STATUS
(
  MESSAGE_NUMBER         VARCHAR2(500 CHAR),
  SAFETY_REPORT_ID       VARCHAR2(500 CHAR),
  CASE_NUM               VARCHAR2(50 CHAR),
  FOLLOWUP               NUMBER,
  REPORT_TYPE            VARCHAR2(500 CHAR),
  DATE_CREATED           DATE,
  DATE_TRANSMITTED       DATE,
  REPORTING_DESTINATION  VARCHAR2(500 CHAR),
  LOCAL_COMPANY_NAME     VARCHAR2(500 CHAR),
  MESSAGE_TYPE           VARCHAR2(500 CHAR),
  E2B_STATUS             NUMBER,
  ACK_STATUS             NUMBER,
  E2B_HTML_NAME          VARCHAR2(200 CHAR),
  ACK_HTML_NAME          VARCHAR2(200 CHAR),
  E2B_ERROR_MESSAGE      VARCHAR2(4000 CHAR),
  DATE_MODIFIED          DATE,
  ACK_ERROR_MESSAGE      VARCHAR2(4000 CHAR),
  ACK_TRANSFORM_STATUS   NUMBER,
  ACK_TRANSFORM_ERR_MSG  VARCHAR2(4000 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/
ALTER TABLE &TRANSFORMPV_USER..E2B_TRANSFORM_STATUS
ADD (TRANSFORM_STATUS_ID NUMBER)
/

ALTER TABLE &TRANSFORMPV_USER..E2B_TRANSFORM_STATUS
 ADD CONSTRAINT E2B_TRANSFORM_STATUS_PK
 PRIMARY KEY
 (TRANSFORM_STATUS_ID)
 /

ALTER TABLE &TRANSFORMPV_USER..E2B_TRANSFORM_STATUS ADD (DELETED NUMBER DEFAULT 0, DELETED_DATE DATE)
/

ALTER TABLE  &TRANSFORMPV_USER..E2B_TRANSFORM_STATUS
 ADD ( ACK2_STATUS NUMBER, ACK2_TRANSFORM_STATUS NUMBER, ACK2_TRANSFORM_ERR_MSG VARCHAR2(4000))
/

ALTER TABLE  &TRANSFORMPV_USER..E2B_TRANSFORM_STATUS
 ADD ( ACK2_HTML_NAME VARCHAR2(200 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_TRANSFORM_STATUS
MODIFY(ACK2_TRANSFORM_ERR_MSG VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_TRANSFORM_STATUS
 ADD (ESM_REPORT_ID  NUMBER)
/

ALTER TABLE &TRANSFORMPV_USER..E2B_TRANSFORM_STATUS
 ADD (E2B_FILE_NAME  VARCHAR2(500 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_TRANSFORM_STATUS
 ADD (ACK_E2B_FILE_NAME  VARCHAR2(500 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_TRANSFORM_STATUS
ADD (AGENCY_ID NUMBER)
/
ALTER TABLE &TRANSFORMPV_USER..E2B_TRANSFORM_STATUS
ADD (MDN_STATUS NUMBER)
/