Prompt Table E2B_CFG_USERS_HIST;
--
-- E2B_CFG_USERS_HIST  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..E2B_CFG_USERS_HIST
(
  USER_ID                  NUMBER(22),
  USER_FULLNAME            VARCHAR2(256 CHAR),
  USER_NAME                VARCHAR2(256 CHAR),
  USER_EMAIL               VARCHAR2(400 CHAR),
  ACCOUNT_DISABLED         NUMBER(22),
  ENTERPRISE_ID            NUMBER(22),
  PWD_CHANGE_ON_IST_LOGIN  NUMBER(22),
  E2BR3APP_PASSWORD        VARCHAR2(2000 CHAR),
  CREATED_DATE             DATE,
  CREATED_BY               NUMBER(22),
  MODIFIED_DATE            DATE,
  MODIFIED_BY              NUMBER(22),
  SAFETY_USER_ID           NUMBER(22),
  DELETED                  NUMBER(22),
  LDAP_USER                NUMBER(22),
  LDAP_SERVER_ID           NUMBER(22),
  ESM_USER                 NUMBER(22),
  GLOBAL_ADMIN             NUMBER(22),
  WORKFLOW_MGR             NUMBER(22),
  DUP_CHECK_NAME           VARCHAR2(400 CHAR),
  VERSION_NUMBER           NUMBER,
  AUDIT_ID                 NUMBER,
  OPERATION_TYPE           NUMBER,
  EFFECTIVE_START_DATE     DATE,
  EFFECTIVE_END_DATE       DATE,
  CURRENT_FLG              NUMBER,
  INSERT_DATE              DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/
