Prompt Table E2B_LDAP_SERVERS;
--
-- E2B_LDAP_SERVERS  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..E2B_LDAP_SERVERS
(
  SERVER_ID        NUMBER(10)                   NOT NULL,
  SERVER_ALIAS     VARCHAR2(255 CHAR),
  SERVER_NAME      VARCHAR2(255 CHAR),
  SERVER_PORT      NUMBER(5),
  BASE_DN          VARCHAR2(255 CHAR),
  TIME_OUT_SEC     NUMBER(5),
  SEARCH_USER_DN   VARCHAR2(255 CHAR),
  SEARCH_PASSWORD  VARCHAR2(255 CHAR),
  SEARCH_KEY       VARCHAR2(255 CHAR),
  SSL              NUMBER(1),
  ANONYMOUS        NUMBER(1),
  DELETED          NUMBER(1),
  CREATED_DATE     DATE,
  CREATED_BY       NUMBER(10),
  MODIFIED_DATE    DATE,
  MODIFIED_BY      NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE &TRANSFORMPV_USER..E2B_LDAP_SERVERS
 ADD CONSTRAINT E2B_LDAP_SERVERS_PK
 PRIMARY KEY
 (SERVER_ID)
 /


ALTER TABLE &TRANSFORMPV_USER..E2B_LDAP_SERVERS ADD (DUP_CHECK_NAME VARCHAR2(500 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_LDAP_SERVERS ADD (
  CONSTRAINT E_DUP_LDAP_NAME_UK
 UNIQUE (DUP_CHECK_NAME))
 /
 
ALTER TABLE &TRANSFORMPV_USER..E2B_LDAP_SERVERS
 ADD (CURRENT_VERSION  NUMBER)
/
 