Prompt Table E2B_CFG_TRASFORM_PROFILES_HIST;
--
-- E2B_CFG_TRASFORM_PROFILES_HIST  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST
(
  O_PROFILE_ID          NUMBER,
  O_PROFILE_NAME        VARCHAR2(200 CHAR),
  O_DELETED             NUMBER                  DEFAULT 0,
  O_DELETED_DATE        DATE,
  O_CREATED_BY          NUMBER,
  O_CREATED_DATE        DATE,
  O_MODIFIED_BY         NUMBER,
  O_MODIFIED_DATE       DATE,
  O_IS_ACK              NUMBER                  DEFAULT 0,
  N_PROFILE_ID          NUMBER,
  N_PROFILE_NAME        VARCHAR2(200 CHAR),
  N_DELETED             NUMBER                  DEFAULT 0,
  N_DELETED_DATE        DATE,
  N_CREATED_BY          NUMBER,
  N_CREATED_DATE        DATE,
  N_MODIFIED_BY         NUMBER,
  N_MODIFIED_DATE       DATE,
  N_IS_ACK              NUMBER                  DEFAULT 0,
  VERSION_NUMBER        NUMBER,
  AUDIT_ID              NUMBER,
  OPERATION_TYPE        VARCHAR2(10 CHAR),
  EFFECTIVE_START_DATE  DATE,
  EFFECTIVE_END_DATE    DATE,
  CURRENT_FLG           NUMBER,
  INSERT_DATE           DATE,
  O_IS_BASE_PROFILE     NUMBER,
  N_IS_BASE_PROFILE     NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST
 ADD (PROFILE_ID  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST
 ADD (PROFILE_NAME  VARCHAR2(800 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST
 ADD (DELETED  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST
 ADD (DELETED_DATE  DATE)
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST
 ADD (CREATED_BY  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST
 ADD (CREATED_DATE  DATE)
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST
 ADD (MODIFIED_BY  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST
 ADD (MODIFIED_DATE  DATE)
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST
 ADD (IS_ACK  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST
 ADD (IS_BASE_PROFILE  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST
 ADD (DUP_CHECK_NAME  VARCHAR2(2000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST
MODIFY(OPERATION_TYPE NUMBER)
/


ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST
 ADD (CURRENT_VERSION  NUMBER)
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST DROP COLUMN O_PROFILE_ID
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST DROP COLUMN O_PROFILE_NAME
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST DROP COLUMN O_DELETED
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST DROP COLUMN O_DELETED_DATE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST DROP COLUMN O_CREATED_BY
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST DROP COLUMN O_CREATED_DATE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST DROP COLUMN O_MODIFIED_BY
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST DROP COLUMN O_MODIFIED_DATE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST DROP COLUMN O_IS_ACK
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST DROP COLUMN N_PROFILE_ID
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST DROP COLUMN N_PROFILE_NAME
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST DROP COLUMN N_DELETED
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST DROP COLUMN N_DELETED_DATE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST DROP COLUMN N_CREATED_BY
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST DROP COLUMN N_CREATED_DATE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST DROP COLUMN N_MODIFIED_BY
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST DROP COLUMN N_MODIFIED_DATE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST DROP COLUMN N_IS_ACK
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST DROP COLUMN O_IS_BASE_PROFILE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES_HIST DROP COLUMN N_IS_BASE_PROFILE
/
