Prompt Table E2B_CFG_TRASFORM_PROFILES;
--
-- E2B_CFG_TRASFORM_PROFILES  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES
(
  PROFILE_ID       NUMBER,
  PROFILE_NAME     VARCHAR2(200 CHAR),
  DELETED          NUMBER                       DEFAULT 0,
  DELETED_DATE     DATE,
  CREATED_BY       NUMBER,
  CREATED_DATE     DATE,
  MODIFIED_BY      NUMBER,
  MODIFIED_DATE    DATE,
  IS_ACK           NUMBER                       DEFAULT 0,
  IS_BASE_PROFILE  NUMBER                       DEFAULT 0
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES
 ADD CONSTRAINT E2B_CFG_TRASFORM_PROFILES_PK
 PRIMARY KEY
 (PROFILE_ID)
 /

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES
ADD (DUP_CHECK_NAME VARCHAR2(500 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES ADD (
  CONSTRAINT E_DUP_PROFILE_NAME_UK
 UNIQUE (DUP_CHECK_NAME))
 /

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_TRASFORM_PROFILES
 ADD (CURRENT_VERSION  NUMBER)
 /
 