Prompt Table E2B_R3_CFG_AGENCY_HIST;
--
-- E2B_R3_CFG_AGENCY_HIST  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
(
  O_AGENCY_NAME           VARCHAR2(200 CHAR),
  O_UPGRADE_XSL           VARCHAR2(1000 CHAR),
  O_DOWNGRADE_XSL         VARCHAR2(1000 CHAR),
  O_ACK_UPGRADE_XSL       VARCHAR2(1000 CHAR),
  O_ACK_DOWNGRADE_XSL     VARCHAR2(1000 CHAR),
  O_UPGRADE_IN_FOLDER     VARCHAR2(1000 CHAR),
  O_UPGRADE_OUT_FOLDER    VARCHAR2(1000 CHAR),
  O_DOWNGRADE_IN_FOLDER   VARCHAR2(1000 CHAR),
  O_DOWNGRADE_OUT_FOLDER  VARCHAR2(1000 CHAR),
  O_BINARY_FOLDER         VARCHAR2(1000 CHAR),
  O_CREATED_BY            NUMBER,
  O_CREATED_DATE          DATE,
  O_MODIFIED_BY           NUMBER,
  O_MODIFIED_DATE         DATE,
  O_DELETED               NUMBER,
  O_DELETED_DATE          DATE,
  N_AGENCY_NAME           VARCHAR2(200 CHAR),
  N_UPGRADE_XSL           VARCHAR2(1000 CHAR),
  N_DOWNGRADE_XSL         VARCHAR2(1000 CHAR),
  N_ACK_UPGRADE_XSL       VARCHAR2(1000 CHAR),
  N_ACK_DOWNGRADE_XSL     VARCHAR2(1000 CHAR),
  N_UPGRADE_IN_FOLDER     VARCHAR2(1000 CHAR),
  N_UPGRADE_OUT_FOLDER    VARCHAR2(1000 CHAR),
  N_DOWNGRADE_IN_FOLDER   VARCHAR2(1000 CHAR),
  N_DOWNGRADE_OUT_FOLDER  VARCHAR2(1000 CHAR),
  N_BINARY_FOLDER         VARCHAR2(1000 CHAR),
  N_CREATED_BY            NUMBER,
  N_CREATED_DATE          DATE,
  N_MODIFIED_BY           NUMBER,
  N_MODIFIED_DATE         DATE,
  N_DELETED               NUMBER,
  N_DELETED_DATE          DATE,
  VERSION_NUMBER          NUMBER,
  AUDIT_ID                NUMBER,
  OPERATION_TYPE          VARCHAR2(10 CHAR),
  EFFECTIVE_START_DATE    DATE,
  EFFECTIVE_END_DATE      DATE,
  CURRENT_FLG             NUMBER,
  INSERT_DATE             DATE,
  O_XSD_FILE              VARCHAR2(500 CHAR),
  N_XSD_FILE              VARCHAR2(500 CHAR),
  O_AGENCY_ID             NUMBER,
  O_DRAFT_E2B_CLASS_ID    NUMBER,
  O_DRAFT_HTML_CLASS_ID   NUMBER,
  O_FINAL_E2B_CLASS_ID    NUMBER,
  O_FINAL_HTML_CLASS_ID   NUMBER,
  O_E2B_PROFILE_ID        NUMBER,
  O_ACK_PROFILE_ID        NUMBER,
  N_AGENCY_ID             NUMBER,
  N_DRAFT_E2B_CLASS_ID    NUMBER,
  N_DRAFT_HTML_CLASS_ID   NUMBER,
  N_FINAL_E2B_CLASS_ID    NUMBER,
  N_FINAL_HTML_CLASS_ID   NUMBER,
  N_E2B_PROFILE_ID        NUMBER,
  N_ACK_PROFILE_ID        NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST ADD (O_ALLOW_MULTI_ACK NUMBER, N_ALLOW_MULTI_ACK NUMBER, O_ENABLED NUMBER, N_ENABLED NUMBER)
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
MODIFY(O_AGENCY_NAME VARCHAR2(200 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
MODIFY(O_UPGRADE_XSL VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
MODIFY(O_DOWNGRADE_XSL VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
MODIFY(O_ACK_UPGRADE_XSL VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
MODIFY(O_ACK_DOWNGRADE_XSL VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
MODIFY(O_UPGRADE_IN_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
MODIFY(O_UPGRADE_OUT_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
MODIFY(O_DOWNGRADE_IN_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
MODIFY(O_DOWNGRADE_OUT_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
MODIFY(O_BINARY_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
MODIFY(N_AGENCY_NAME VARCHAR2(200 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
MODIFY(N_UPGRADE_XSL VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
MODIFY(N_DOWNGRADE_XSL VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
MODIFY(N_ACK_UPGRADE_XSL VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
MODIFY(N_ACK_DOWNGRADE_XSL VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
MODIFY(N_UPGRADE_IN_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
MODIFY(N_UPGRADE_OUT_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
MODIFY(N_DOWNGRADE_IN_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
MODIFY(N_DOWNGRADE_OUT_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
MODIFY(N_BINARY_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
MODIFY(OPERATION_TYPE VARCHAR2(20 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
MODIFY(O_XSD_FILE VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
MODIFY(N_XSD_FILE VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (AGENCY_ID  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (AGENCY_NAME  VARCHAR2(800 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (UPGRADE_XSL  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (DOWNGRADE_XSL  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (ACK_UPGRADE_XSL  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (ACK_DOWNGRADE_XSL  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (UPGRADE_IN_FOLDER  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (UPGRADE_OUT_FOLDER  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (DOWNGRADE_IN_FOLDER  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (DOWNGRADE_OUT_FOLDER  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (CREATED_BY  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (CREATED_DATE  DATE)
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (MODIFIED_BY  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (MODIFIED_DATE  DATE)
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (DELETED  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (DELETED_DATE  DATE)
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (FINAL_E2B_CLASS_ID  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (FINAL_HTML_CLASS_ID  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (E2B_PROFILE_ID  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (ACK_PROFILE_ID  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (XSD_FILE  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (ENABLED  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (ALLOW_MULTI_ACK  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (EXP_ATTACHMENT_PATH  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (IMP_ATTACHMENT_PATH  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (IMP_ATTACHMENT_CLASS_ID  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
 ADD (FINAL_FILE_FORMAT  VARCHAR2(400 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST
MODIFY(OPERATION_TYPE NUMBER)
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_AGENCY_NAME
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_UPGRADE_XSL
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_DOWNGRADE_XSL
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_ACK_UPGRADE_XSL
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_ACK_DOWNGRADE_XSL
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_UPGRADE_IN_FOLDER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_UPGRADE_OUT_FOLDER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_DOWNGRADE_IN_FOLDER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_DOWNGRADE_OUT_FOLDER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_BINARY_FOLDER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_CREATED_BY
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_CREATED_DATE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_MODIFIED_BY
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_MODIFIED_DATE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_DELETED
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_DELETED_DATE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_AGENCY_NAME
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_UPGRADE_XSL
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_DOWNGRADE_XSL
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_ACK_UPGRADE_XSL
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_ACK_DOWNGRADE_XSL
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_UPGRADE_IN_FOLDER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_UPGRADE_OUT_FOLDER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_DOWNGRADE_IN_FOLDER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_DOWNGRADE_OUT_FOLDER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_BINARY_FOLDER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_CREATED_BY
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_CREATED_DATE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_MODIFIED_BY
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_MODIFIED_DATE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_DELETED
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_DELETED_DATE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_XSD_FILE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_XSD_FILE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_AGENCY_ID
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_DRAFT_E2B_CLASS_ID
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_DRAFT_HTML_CLASS_ID
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_FINAL_E2B_CLASS_ID
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_FINAL_HTML_CLASS_ID
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_E2B_PROFILE_ID
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_ACK_PROFILE_ID
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_AGENCY_ID
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_DRAFT_E2B_CLASS_ID
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_DRAFT_HTML_CLASS_ID
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_FINAL_E2B_CLASS_ID
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_FINAL_HTML_CLASS_ID
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_E2B_PROFILE_ID
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_ACK_PROFILE_ID
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_ALLOW_MULTI_ACK
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_ALLOW_MULTI_ACK
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN O_ENABLED
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY_HIST DROP COLUMN N_ENABLED
/
