Prompt Table E2B_CFG_USERS;
--
-- E2B_CFG_USERS  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..E2B_CFG_USERS
(
  USER_ID                  NUMBER               NOT NULL,
  USER_FULLNAME            VARCHAR2(64 CHAR),
  USER_NAME                VARCHAR2(64 CHAR),
  USER_EMAIL               VARCHAR2(100 CHAR),
  ACCOUNT_DISABLED         NUMBER,
  ENTERPRISE_ID            NUMBER,
  PWD_CHANGE_ON_IST_LOGIN  NUMBER               DEFAULT 1,
  E2BR3APP_PASSWORD        VARCHAR2(500 CHAR),
  CREATED_DATE             DATE,
  CREATED_BY               NUMBER,
  MODIFIED_DATE            DATE,
  MODIFIED_BY              NUMBER,
  SAFETY_USER_ID           NUMBER,
  DELETED                  NUMBER               DEFAULT 0,
  LDAP_USER                NUMBER               DEFAULT 0,
  LDAP_SERVER_ID           NUMBER,
  ESM_USER                 NUMBER,
  GLOBAL_ADMIN             NUMBER               DEFAULT 0,
  WORKFLOW_MGR			   NUMBER				DEFAULT 0
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_USERS
 ADD CONSTRAINT E2B_CFG_USERS_PK
 PRIMARY KEY
 (USER_ID)
 /

ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_USERS ADD (DUP_CHECK_NAME VARCHAR2(100 CHAR))
/
 
ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_USERS ADD (
  CONSTRAINT Q_DUP_USER_NAME_UK
 UNIQUE (DUP_CHECK_NAME, ENTERPRISE_ID))
 /
 
ALTER TABLE &TRANSFORMPV_USER..E2B_CFG_USERS
 ADD (CURRENT_VERSION  NUMBER)
 /
 