Prompt Table E2B_R2R3MAPPING_HIST;
--
-- E2B_R2R3MAPPING_HIST  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST
(
  O_R2_ELEMENT_NUM       VARCHAR2(50 CHAR),
  O_R2_ELEMENT           VARCHAR2(500 CHAR),
  O_R2_XPATH             VARCHAR2(500 CHAR),
  O_R3_ELEMENT_NUM       VARCHAR2(500 CHAR),
  O_R3_ELEMENT           VARCHAR2(1000 CHAR),
  O_R3_XPATH             VARCHAR2(4000 CHAR),
  O_R3_NULL_XPATH        VARCHAR2(4000 CHAR),
  O_REPEAT_INFO          VARCHAR2(15 CHAR),
  O_PROFILE_ID           NUMBER,
  O_SORT_ID              NUMBER,
  O_SEQ_NUM              NUMBER,
  O_CREATED_BY           NUMBER,
  O_CREATED_DATE         DATE,
  O_MODIFIED_BY          NUMBER,
  O_MODIFIED_DATE        DATE,
  O_DELETED              NUMBER                 DEFAULT 0,
  N_R2_ELEMENT_NUM       VARCHAR2(50 CHAR),
  N_R2_ELEMENT           VARCHAR2(500 CHAR),
  N_R2_XPATH             VARCHAR2(500 CHAR),
  N_R3_ELEMENT_NUM       VARCHAR2(500 CHAR),
  N_R3_ELEMENT           VARCHAR2(1000 CHAR),
  N_R3_XPATH             VARCHAR2(4000 CHAR),
  N_R3_NULL_XPATH        VARCHAR2(4000 CHAR),
  N_REPEAT_INFO          VARCHAR2(15 CHAR),
  N_PROFILE_ID           NUMBER,
  N_SORT_ID              NUMBER,
  N_SEQ_NUM              NUMBER,
  N_CREATED_BY           NUMBER,
  N_CREATED_DATE         DATE,
  N_MODIFIED_BY          NUMBER,
  N_MODIFIED_DATE        DATE,
  N_DELETED              NUMBER                 DEFAULT 0,
  VERSION_NUMBER         NUMBER,
  AUDIT_ID               NUMBER,
  OPERATION_TYPE         VARCHAR2(10 CHAR),
  EFFECTIVE_START_DATE   DATE,
  EFFECTIVE_END_DATE     DATE,
  CURRENT_FLG            NUMBER,
  INSERT_DATE            DATE,
  O_HEADER               NUMBER,
  N_HEADER               NUMBER,
  O_E2B_ELEMENT_NUM_REF  VARCHAR2(100 CHAR),
  N_E2B_ELEMENT_NUM_REF  VARCHAR2(100 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST
 ADD (R2_ELEMENT_NUM  VARCHAR2(50 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST
 ADD (R2_ELEMENT  VARCHAR2(500 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST
 ADD (R2_XPATH  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST
 ADD (R3_ELEMENT_NUM  VARCHAR2(50 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST
 ADD (R3_ELEMENT  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST
 ADD (R3_XPATH  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST
 ADD (R3_NULL_XPATH  VARCHAR2(4000 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST
 ADD (REPEAT_INFO  VARCHAR2(15 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST
 ADD (PROFILE_ID  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST
 ADD (SORT_ID  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST
 ADD (SEQ_NUM  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST
 ADD (CREATED_BY  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST
 ADD (CREATED_DATE  DATE)
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST
 ADD (MODIFIED_BY  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST
 ADD (MODIFIED_DATE  DATE)
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST
 ADD (DELETED  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST
 ADD (HEADER  NUMBER(22))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST
 ADD (E2B_ELEMENT_NUM_REF  VARCHAR2(400 CHAR))
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST
MODIFY(OPERATION_TYPE NUMBER)
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN O_R2_ELEMENT_NUM
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN O_R2_ELEMENT
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN O_R2_XPATH
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN O_R3_ELEMENT_NUM
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN O_R3_ELEMENT
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN O_R3_XPATH
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN O_R3_NULL_XPATH
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN O_REPEAT_INFO
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN O_PROFILE_ID
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN O_SORT_ID
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN O_SEQ_NUM
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN O_CREATED_BY
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN O_CREATED_DATE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN O_MODIFIED_BY
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN O_MODIFIED_DATE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN O_DELETED
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN N_R2_ELEMENT_NUM
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN N_R2_ELEMENT
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN N_R2_XPATH
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN N_R3_ELEMENT_NUM
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN N_R3_ELEMENT
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN N_R3_XPATH
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN N_R3_NULL_XPATH
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN N_REPEAT_INFO
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN N_PROFILE_ID
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN N_SORT_ID
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN N_SEQ_NUM
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN N_CREATED_BY
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN N_CREATED_DATE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN N_MODIFIED_BY
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN N_MODIFIED_DATE
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN N_DELETED
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN O_HEADER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN N_HEADER
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN O_E2B_ELEMENT_NUM_REF
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING_HIST DROP COLUMN N_E2B_ELEMENT_NUM_REF
/
