Prompt Table E2B_R2R3MAPPING;
--
-- E2B_R2R3MAPPING  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING
(
  R2_ELEMENT_NUM       VARCHAR2(50 CHAR),
  R2_ELEMENT           VARCHAR2(500 CHAR),
  R2_XPATH             VARCHAR2(4000 CHAR),
  R3_ELEMENT_NUM       VARCHAR2(50 CHAR),
  R3_ELEMENT           VARCHAR2(4000 CHAR),
  R3_XPATH             VARCHAR2(4000 CHAR),
  R3_NULL_XPATH        VARCHAR2(4000 CHAR),
  REPEAT_INFO          VARCHAR2(15 CHAR),
  PROFILE_ID           NUMBER,
  SORT_ID              NUMBER,
  SEQ_NUM              NUMBER,
  CREATED_BY           NUMBER,
  CREATED_DATE         DATE,
  MODIFIED_BY          NUMBER,
  MODIFIED_DATE        DATE,
  DELETED              NUMBER                   DEFAULT 0,
  HEADER               NUMBER,
  E2B_ELEMENT_NUM_REF  VARCHAR2(100 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R2R3MAPPING
 ADD CONSTRAINT E2B_R2R3MAPPING_PK
 PRIMARY KEY
 (PROFILE_ID, SEQ_NUM)
 /
