Prompt Table E2B_R3_CFG_SYSTEM;
--
-- E2B_R3_CFG_SYSTEM  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM
(
  APPLICATION     VARCHAR2(200 CHAR),
  BFC_IN_FOLDER   VARCHAR2(1000 CHAR),
  BFC_OUT_FOLDER  VARCHAR2(1000 CHAR),
  BFC_BKP_FOLDER  VARCHAR2(1000 CHAR),
  ERROR_FOLDER    VARCHAR2(1000 CHAR),
  LOG_FOLDER      VARCHAR2(1000 CHAR),
  ACK_IDENTIFIER  VARCHAR2(200 CHAR),
  CREATED_BY      NUMBER,
  CREATED_DATE    DATE,
  MODIFIED_BY     NUMBER,
  MODIFIFED_DATE  DATE,
  DELETED         NUMBER                        DEFAULT 0,
  DELETED_DATE    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM
 ADD CONSTRAINT E2B_R3_CFG_SYSTEM_PK
 PRIMARY KEY
 (APPLICATION)
 /

 ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM ADD(HTML_FOLDER VARCHAR2(500), PDF_TEMPLATE_FOLDER VARCHAR2(500))
 /
 
 ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM
MODIFY(APPLICATION VARCHAR2(200 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM
MODIFY(BFC_IN_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM
MODIFY(BFC_OUT_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM
MODIFY(BFC_BKP_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM
MODIFY(ERROR_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM
MODIFY(LOG_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM
MODIFY(ACK_IDENTIFIER VARCHAR2(200 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM
MODIFY(HTML_FOLDER VARCHAR2(4000 CHAR))
/


ALTER TABLE &TRANSFORMPV_USER..E2B_R3_CFG_SYSTEM
MODIFY(PDF_TEMPLATE_FOLDER VARCHAR2(4000 CHAR))
/