Prompt Table E2B_CFG_AUDIT_TAB_RELATIONS;
--
-- E2B_CFG_AUDIT_TAB_RELATIONS  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..E2B_CFG_AUDIT_TAB_RELATIONS
(
  AUDIT_TAB_RELATION_ID  NUMBER,
  PAGE_ID                NUMBER,
  TABLE_ID               NUMBER,
  TABLE_NAME             VARCHAR2(30 CHAR),
  HIST_TABLE_NAME        VARCHAR2(50 CHAR),
  TABLE_TYPE             NUMBER,
  PK_ID_COL              VARCHAR2(30 CHAR),
  PK_DISPLAY_COL         VARCHAR2(30 CHAR),
  PARENT_TBL_ID          NUMBER,
  DELETED                NUMBER,
  DELETED_DATE           DATE,
  CREATED_DATE           DATE,
  MODIFIED_DATE          DATE,
  CREATED_BY             NUMBER,
  MODIFIED_BY            NUMBER,
  ENABLED                NUMBER,
  AUDIT_KEY_FILTER_COL   VARCHAR2(100 CHAR),
  TABLE_SCHEMA_OWNER     VARCHAR2(200 CHAR),
  ENTERPRISE_ID          NUMBER,
  GUI_PARENT_TEXT        VARCHAR2(500 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/
