Prompt Table ETL_MASTER;
--
-- ETL_MASTER  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..ETL_MASTER
(
  ETL_ID        NUMBER(10),
  ETL_NAME      VARCHAR2(500 CHAR),
  DESCRIPTION   VARCHAR2(500 CHAR),
  ENABLED       NUMBER(10),
  DELETED_DATE  DATE,
  INSERT_DATE   DATE,
  UPDATE_DATE   DATE,
  MAX_BATCHES   NUMBER,
  FREQUENCY     VARCHAR2(100 CHAR),
  START_DATE    DATE,
  DAYS_IN_WEEK  VARCHAR2(50 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

ALTER TABLE &TRANSFORMPV_USER..ETL_MASTER
 ADD CONSTRAINT ETL_MASTER_PK
 PRIMARY KEY
 (ETL_ID)
 /

ALTER TABLE &TRANSFORMPV_USER..ETL_MASTER ADD (DELETED NUMBER DEFAULT 0)
/

ALTER TABLE &TRANSFORMPV_USER..ETL_MASTER
 ADD (CREATED_DATE  DATE)
/

ALTER TABLE &TRANSFORMPV_USER..ETL_MASTER
 ADD (MODIFIED_DATE  DATE)
/

ALTER TABLE &TRANSFORMPV_USER..ETL_MASTER
 ADD (CURRENT_VERSION  NUMBER)
/

ALTER TABLE &TRANSFORMPV_USER..ETL_MASTER
 ADD (CREATED_BY  NUMBER)
/

ALTER TABLE &TRANSFORMPV_USER..ETL_MASTER
 ADD (MODIFIED_BY  NUMBER)
/

ALTER TABLE &TRANSFORMPV_USER..ETL_MASTER DROP COLUMN INSERT_DATE
/

ALTER TABLE &TRANSFORMPV_USER..ETL_MASTER DROP COLUMN UPDATE_DATE
/