Prompt Table ETL_CONSTANTS;
--
-- ETL_CONSTANTS  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..ETL_CONSTANTS
(
  CONSTANT_ID  NUMBER(10),
  KEY          VARCHAR2(100 CHAR),
  VALUE        VARCHAR2(500 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

ALTER TABLE &TRANSFORMPV_USER..ETL_CONSTANTS
 ADD CONSTRAINT ETL_CONSTANTS_PK
 PRIMARY KEY
 (CONSTANT_ID)
 /

ALTER TABLE &TRANSFORMPV_USER..ETL_CONSTANTS ADD (DELETED NUMBER DEFAULT 0, DELETED_DATE DATE)
/

