Prompt Table ETL_CFG_PROCS;
--
-- ETL_CFG_PROCS  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..ETL_CFG_PROCS
(
  CFG_PROC_ID      NUMBER(10),
  ETL_ID           NUMBER(10),
  EXECUTION_ORDER  NUMBER(10),
  ENABLED          NUMBER(10),
  DESCRIPTION      VARCHAR2(500 CHAR),
  DELETED_DATE     DATE,
  INSERT_DATE      DATE,
  UPDATE_DATE      DATE,
  ETL_MODULE       VARCHAR2(100 CHAR),
  PROC_TYPE        VARCHAR2(100 CHAR),
  PACKAGE_NAME     VARCHAR2(100 CHAR),
  PROCEDURE_NAME   VARCHAR2(100 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE &TRANSFORMPV_USER..ETL_CFG_PROCS
 ADD CONSTRAINT ETL_CFG_PROCS_PK
 PRIMARY KEY
 (CFG_PROC_ID)
 /

ALTER TABLE &TRANSFORMPV_USER..ETL_CFG_PROCS ADD (DELETED NUMBER DEFAULT 0)
/
