Prompt Table ETL_MASTER_HIST;
--
-- ETL_MASTER_HIST  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..ETL_MASTER_HIST
(
  ETL_ID                NUMBER(22),
  ETL_NAME              VARCHAR2(2000 CHAR),
  DESCRIPTION           VARCHAR2(500 CHAR),
  ENABLED               NUMBER(22),
  DELETED_DATE          DATE,
  CREATED_DATE          DATE,
  MODIFIED_DATE         DATE,
  MAX_BATCHES           NUMBER(22),
  FREQUENCY             VARCHAR2(400 CHAR),
  START_DATE            DATE,
  DAYS_IN_WEEK          VARCHAR2(200 CHAR),
  DELETED               NUMBER(22),
  VERSION_NUMBER        NUMBER,
  AUDIT_ID              NUMBER,
  OPERATION_TYPE        NUMBER,
  EFFECTIVE_START_DATE  DATE,
  EFFECTIVE_END_DATE    DATE,
  CURRENT_FLG           NUMBER,
  INSERT_DATE           DATE,
  CREATED_BY            NUMBER,
  MODIFIED_BY           NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/
