Prompt Table ETL_EXECUTION_LOG;
--
-- ETL_EXECUTION_LOG  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..ETL_EXECUTION_LOG
(
  EXECUTION_ID          NUMBER(10),
  EXECUTION_SEQ         NUMBER,
  ETL_ID                NUMBER(10),
  ETL_TYPE              VARCHAR2(100 CHAR),
  ETL_AREA              VARCHAR2(100 CHAR),
  PROC_ID               NUMBER,
  PROC_START_TIME       TIMESTAMP(6),
  PROC_END_TIME         TIMESTAMP(6),
  NO_OF_ROWS_PROCESSED  NUMBER,
  LOG_MESSAGE           VARCHAR2(1000 CHAR),
  LOG_TIME              TIMESTAMP(6),
  STATUS                NUMBER,
  BATCH_NO              NUMBER,
  PACKAGE_NAME          VARCHAR2(100 CHAR),
  PROC_NAME             VARCHAR2(100 CHAR),
  LOAD_DATA_CATEGORY    VARCHAR2(200 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

ALTER TABLE &TRANSFORMPV_USER..ETL_EXECUTION_LOG
 ADD CONSTRAINT ETL_EXECUTION_LOG_PK
 PRIMARY KEY
 (EXECUTION_ID, EXECUTION_SEQ)
 /

ALTER TABLE &TRANSFORMPV_USER..ETL_EXECUTION_LOG ADD (DELETED NUMBER DEFAULT 0, DELETED_DATE DATE)
/
