Prompt Table ETL_TRACE_LOG;
--
-- ETL_TRACE_LOG  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..ETL_TRACE_LOG
(
  LOG_ID            NUMBER(10),
  LOG_LEVEL         NUMBER(10),
  LOG_TYPE_ID       NUMBER(10),
  ETL_ID            NUMBER(10),
  CASE_ID           NUMBER(10),
  CASE_NUM          VARCHAR2(50 CHAR),
  STEP_NUMBER       NUMBER,
  PROC_NAME         VARCHAR2(100 CHAR),
  PACKAGE_NAME      VARCHAR2(100 CHAR),
  LOG_MESSAGE       VARCHAR2(4000 CHAR),
  COMMENTS          VARCHAR2(4000 CHAR),
  MESSAGE_ID        NUMBER(10),
  LOG_TIME          TIMESTAMP(6),
  LOG_SQL_CODE      VARCHAR2(500 CHAR),
  ETL_EXECUTION_ID  NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

ALTER TABLE &TRANSFORMPV_USER..ETL_TRACE_LOG
 ADD CONSTRAINT ETL_TRACE_LOG_PK
 PRIMARY KEY
 (LOG_ID)
 /

ALTER TABLE &TRANSFORMPV_USER..ETL_TRACE_LOG ADD (DELETED NUMBER DEFAULT 0, DELETED_DATE DATE)
/


