Prompt Table ETL_CFG_USER_GROUPS;
--
-- ETL_CFG_USER_GROUPS  (Table) 
CREATE TABLE &TRANSFORMPV_USER..ETL_CFG_USER_GROUPS
(
  ETL_GROUP_ID   NUMBER,
  ETL_ID         NUMBER,
  GROUP_ID       NUMBER,
  DELETED        NUMBER                         DEFAULT 0,
  CREATED_BY     NUMBER,
  CREATED_DATE   DATE,
  MODIFIED_BY    NUMBER,
  MODIFIED_DATE  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

ALTER TABLE &TRANSFORMPV_USER..ETL_CFG_USER_GROUPS ADD (
  PRIMARY KEY
 (ETL_GROUP_ID))
/

