Prompt Table ETL_LOAD_WINDOW;
--
-- ETL_LOAD_WINDOW  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..ETL_LOAD_WINDOW
(
  ETL_ID      NUMBER,
  DATE_FROM   DATE,
  DATE_TO     DATE,
  HOURS_DIFF  NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

ALTER TABLE &TRANSFORMPV_USER..ETL_LOAD_WINDOW
 ADD CONSTRAINT ETL_LOAD_WINDOW_PK
 PRIMARY KEY
 (ETL_ID)
 /

ALTER TABLE &TRANSFORMPV_USER..ETL_LOAD_WINDOW ADD (DELETED NUMBER DEFAULT 0, DELETED_DATE DATE)
/
