Prompt Table GT_AUDIT_VERSION_DTL;
--
-- GT_AUDIT_VERSION_DTL  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE &TRANSFORMPV_USER..GT_AUDIT_VERSION_DTL
(
  VERSION_NUMBER     NUMBER,
  PRIMARY_KEY_COL    VARCHAR2(200 CHAR),
  PRIMARY_KEY_VALUE  NUMBER,
  COL_NAME           VARCHAR2(200 CHAR),
  COL_VALUE          VARCHAR2(4000 CHAR),
  OPERATION_TYPE     NUMBER,
  MODIFIED_DATE      DATE,
  USER_ID            NUMBER,
  USER_NAME          VARCHAR2(300 CHAR),
  TABLE_NAME         VARCHAR2(300 CHAR),
  ENTERPRISE_ID      NUMBER                     DEFAULT SYS_CONTEXT('QUADRANT_CONTEXT','ENTERPRISE_ID'),
  CHILD_RANK         NUMBER
)
ON COMMIT PRESERVE ROWS
NOCACHE
ENABLE ROW MOVEMENT
/
