Prompt Table GT_AUDIT_LOG_REVISION_DETAILS;
--
-- GT_AUDIT_LOG_REVISION_DETAILS  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE &TRANSFORMPV_USER..GT_AUDIT_LOG_REVISION_DETAILS
(
  OPERATION              VARCHAR2(100 CHAR),
  AUDIT_DATA             VARCHAR2(4000 CHAR),
  AUDIT_CATEGORY         VARCHAR2(200 CHAR),
  REVISION_NUMBER        NUMBER,
  USER_ID                NUMBER,
  USER_NAME              VARCHAR2(200 CHAR),
  DATETIME               DATE,
  AUDIT_KEY              VARCHAR2(4000 CHAR),
  AUDIT_VERSION_SEQ_NUM  NUMBER,
  TABLE_NAME             VARCHAR2(100 CHAR),
  COLUMN_NAME            VARCHAR2(100 CHAR),
  OLD_VALUE              VARCHAR2(4000 CHAR),
  NEW_VALUE              VARCHAR2(4000 CHAR),
  DB_COLUMN_ID           NUMBER
)
ON COMMIT PRESERVE ROWS
NOCACHE
/


