Prompt Table GT_AUDIT_LOG_PAGE_ENTITY;
--
-- GT_AUDIT_LOG_PAGE_ENTITY  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE &TRANSFORMPV_USER..GT_AUDIT_LOG_PAGE_ENTITY
(
  OPERATION              VARCHAR2(100 CHAR),
  AUDIT_DATA             VARCHAR2(2000 CHAR),
  AUDIT_CATEGORY         VARCHAR2(200 CHAR),
  REVISION_NUMBER        NUMBER,
  USER_ID                NUMBER,
  USER_NAME              VARCHAR2(200 CHAR),
  DATETIME               DATE,
  AUDIT_KEY              VARCHAR2(1000 CHAR),
  AUDIT_VERSION_SEQ_NUM  NUMBER
)
ON COMMIT PRESERVE ROWS
NOCACHE
/


