Prompt Table GT_DECODE_VIEW_LIST;
--
-- GT_DECODE_VIEW_LIST  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE &TRANSFORMPV_USER..GT_DECODE_VIEW_LIST
(
  DECODE_TYPE  VARCHAR2(200 CHAR),
  R2_R3_FLAG   VARCHAR2(500 CHAR),
  E2B_VALUE    VARCHAR2(1000 CHAR),
  E2B_VALUE_J  VARCHAR2(1000 CHAR),
  E2B_CODE     VARCHAR2(100 CHAR),
  DTD_ELEMENT  VARCHAR2(100 CHAR)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/


