Prompt Table GT_VERSION_DTL_TEMP;
--
-- GT_VERSION_DTL_TEMP  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE &TRANSFORMPV_USER..GT_VERSION_DTL_TEMP
(
  COL_NAME        VARCHAR2(4000 CHAR),
  VERSION1        VARCHAR2(4000 CHAR),
  VERSION2        VARCHAR2(4000 CHAR),
  VERSION3        VARCHAR2(4000 CHAR),
  VERSION4        VARCHAR2(4000 CHAR),
  VERSION5        VARCHAR2(4000 CHAR),
  VERSION6        VARCHAR2(4000 CHAR),
  VERSION7        VARCHAR2(4000 CHAR),
  VERSION8        VARCHAR2(4000 CHAR),
  VERSION9        VARCHAR2(4000 CHAR),
  VERSION10       VARCHAR2(4000 CHAR),
  VERSION_NUMBER  VARCHAR2(10 CHAR),
  OPERATION_TYPE  VARCHAR2(200 CHAR),
  INSERT_DATE     VARCHAR2(200 CHAR),
  AUDITDATA       VARCHAR2(400 CHAR),
  USER_NAME       VARCHAR2(300 CHAR),
  TABLE_NAME      VARCHAR2(200 CHAR),
  ROW_NUMBER      NUMBER,
  ENTERPRISE_ID   NUMBER,
  CHILD_RANK      NUMBER
)
ON COMMIT PRESERVE ROWS
NOCACHE
ENABLE ROW MOVEMENT
/
