Prompt Table R2_FACTORY_DATA;
--
-- R2_FACTORY_DATA  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..R2_FACTORY_DATA
(
  DATA_ID         NUMBER,
  PROFILE_ID      NUMBER,
  SEQ_NUM         NUMBER,
  SORT_ID         NUMBER,
  ELEMENT_NUMBER  VARCHAR2(200 CHAR),
  ELEMENT_VALUE   VARCHAR2(500 CHAR),
  DELETED         NUMBER                        DEFAULT 0,
  DELETED_DATE    DATE,
  CREATED_BY      NUMBER,
  CREATED_DATE    DATE,
  MODIFIED_BY     NUMBER,
  MODIFIED_DATE   DATE,
  ELEMENT_NAME    VARCHAR2(200 CHAR),
  ELEMENT_DESC    VARCHAR2(500 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE &TRANSFORMPV_USER..R2_FACTORY_DATA
 ADD CONSTRAINT R2_FACTORY_DATA_PK
 PRIMARY KEY
 (DATA_ID)
 /

