Prompt Table R2_FACTORY_DATA_HIST;
--
-- R2_FACTORY_DATA_HIST  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..R2_FACTORY_DATA_HIST
(
  DATA_ID               NUMBER(22),
  PROFILE_ID            NUMBER(22),
  SEQ_NUM               NUMBER(22),
  SORT_ID               NUMBER(22),
  ELEMENT_NUMBER        VARCHAR2(800 CHAR),
  ELEMENT_VALUE         VARCHAR2(2000 CHAR),
  DELETED               NUMBER(22),
  DELETED_DATE          DATE,
  CREATED_BY            NUMBER(22),
  CREATED_DATE          DATE,
  MODIFIED_BY           NUMBER(22),
  MODIFIED_DATE         DATE,
  ELEMENT_NAME          VARCHAR2(800 CHAR),
  ELEMENT_DESC          VARCHAR2(2000 CHAR),
  VERSION_NUMBER        NUMBER,
  AUDIT_ID              NUMBER,
  OPERATION_TYPE        NUMBER,
  EFFECTIVE_START_DATE  DATE,
  EFFECTIVE_END_DATE    DATE,
  CURRENT_FLG           NUMBER,
  INSERT_DATE           DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/
