Prompt Table R2R3_NULL_FLAVOUR_MAPPING;
--
-- R2R3_NULL_FLAVOUR_MAPPING  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..R2R3_NULL_FLAVOUR_MAPPING
(
  MAPPING_ID     NUMBER,
  PROFILE_ID     NUMBER,
  R2_DATA_ID     NUMBER,
  R3_DATA_ID     NUMBER,
  DELETED        NUMBER                         DEFAULT 0,
  DELETED_DATE   DATE,
  CREATED_BY     NUMBER,
  CREATED_DATE   DATE,
  MODIFIED_BY    NUMBER,
  MODIFIED_DATE  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

ALTER TABLE &TRANSFORMPV_USER..R2R3_NULL_FLAVOUR_MAPPING
 ADD CONSTRAINT R2R3_NULL_FLAVOUR_MAPPING_PK
 PRIMARY KEY
 (MAPPING_ID)
 /



