Prompt Table SAFETYREPORT_R3VIEW;
--
-- SAFETYREPORT_R3VIEW  (Table) 
--
CREATE TABLE &TRANSFORMPV_USER..SAFETYREPORT_R3VIEW
(
  REPORT_ID                     NUMBER          NOT NULL,
  SAFETYREPORTID                VARCHAR2(100 CHAR),
  SAFETYREPORTVERSION           VARCHAR2(2 CHAR),
  RECEIVER_AGENCY               VARCHAR2(100 CHAR),
  CASE_XREF                     NUMBER,
  AGENCY_ID                     NUMBER,
  PROCESSED                     NUMBER,
  E2B                           CLOB            DEFAULT EMPTY_CLOB(),
  FILENAME                      VARCHAR2(250 CHAR),
  ENTERPRISE_ID                 NUMBER,
  CREATED_DATE					DATE DEFAULT SYSDATE,
  MODIFIED_DATE					DATE)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


ALTER TABLE &TRANSFORMPV_USER..SAFETYREPORT_R3VIEW ADD (DELETED NUMBER DEFAULT 0, DELETED_DATE DATE)
/
ALTER TABLE &TRANSFORMPV_USER..SAFETYREPORT_R3VIEW
 ADD CONSTRAINT SAFETYREPORT_R3VIEW_PK
 PRIMARY KEY
 (REPORT_ID)
/

ALTER TABLE &TRANSFORMPV_USER..SAFETYREPORT_R3VIEW ADD (E2B_REPORT_STATUS NUMBER)
/
