CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_LM_CLASSIFICATION FOR &ARGUS_APP_USER..V$LM_CLASSIFICATION
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_CFG_LDAP_SERVERS FOR &ARGUS_APP_USER..V$CFG_LDAP_SERVERS
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..ESM_CFG_MESSAGE_TYPE FOR &ESM_OWNER_USER..V$CFG_MESSAGE_TYPE
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..E2B_LM_REGULATORY_CONTACT FOR &ARGUS_APP_USER..V$LM_REGULATORY_CONTACT
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_LM_AGE_GROUPS FOR &ARGUS_APP_USER..V$LM_AGE_GROUPS
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_LM_CASE_CLASSIFICATION FOR &ARGUS_APP_USER..V$LM_CASE_CLASSIFICATION
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_LM_AGE_UNITS FOR &ARGUS_APP_USER..V$LM_AGE_UNITS
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_LM_REPORT_TYPE FOR &ARGUS_APP_USER..V$LM_REPORT_TYPE
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_LM_GENDER FOR &ARGUS_APP_USER..V$LM_GENDER
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_LM_REPORTER_TYPE FOR &TRANSFORMPV_USER..VW_LM_REPORTER_TYPE
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_LM_EVT_OUTCOME FOR &ARGUS_APP_USER..V$LM_EVT_OUTCOME
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_LM_DOSE_UNITS FOR &ARGUS_APP_USER..V$LM_DOSE_UNITS
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_LM_ACTION_TAKEN FOR &ARGUS_APP_USER..V$LM_ACTION_TAKEN
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_CFG_SAME_E2B_CODE FOR &ESM_OWNER_USER..V$CFG_SAME_E2B_CODE
/
--CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..F_CUSTM_E2BR3_ATTACH FOR &ARGUS_APP_USER..V$F_CUSTM_E2BR3_ATTACH
--/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_CFG_USERS FOR &ARGUS_APP_USER..V$CFG_USERS
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_CFG_GROUPS FOR &ARGUS_APP_USER..V$CFG_GROUPS
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_CFG_RECEIVER FOR &ESM_OWNER_USER..V$CFG_RECEIVER
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_CMN_REG_REPORTS FOR &ARGUS_APP_USER..V$CMN_REG_REPORTS
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_CASE_REG_REPORTS FOR &ARGUS_APP_USER..V$CASE_REG_REPORTS
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_CFG_USER_GROUPS FOR &ARGUS_APP_USER..V$CFG_USER_GROUPS
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_LM_REGULATORY_CONTACT FOR &ARGUS_APP_USER..V$LM_REGULATORY_CONTACT
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_CMN_FIELDS FOR &ARGUS_APP_USER..V$CMN_FIELDS
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_LM_ESM_ARGUS_MAPPING FOR &ESM_OWNER_USER..V$LM_ESM_ARGUS_MAPPING
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_LM_COUNTRIES FOR &TRANSFORMPV_USER..VW_LM_COUNTRIES
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_CL_DEVICE_OPERATOR FOR &TRANSFORMPV_USER..VW_CL_DEVICE_OPERATOR
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_LM_ADMIN_ROUTE FOR &ARGUS_APP_USER..V$LM_ADMIN_ROUTE
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_CASE_MASTER FOR &ARGUS_APP_USER..V$CASE_MASTER
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_ACKNOWLEDGMENT FOR &ESM_OWNER_USER..V$ACKNOWLEDGMENT
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_MEDDRA_PREF_TERM_LLT FOR &TRANSFORMPV_USER..VW_MEDDRA_PREF_TERM_LLT
/
CREATE OR REPLACE PUBLIC SYNONYM VIT_E2B_R3_CFG_AGENCY FOR &TRANSFORMPV_USER..E2B_R3_CFG_AGENCY
/
CREATE OR REPLACE SYNONYM &TRANSFORMPV_USER..SYN_MEDDRA_PREF_TERM FOR &TRANSFORMPV_USER..VW_MEDDRA_PREF_TERM
/
