Insert into &TRANSFORMPV_USER..E2B_CMN_ERROR_MESSAGES
   (ERROR_NUMBER, ERROR_MESSAGE, ENABLED)
 Values
   (20002, 'Cannot complete operation. Your user account is either disabled or deleted. Please contact system administrator.', 1);
Insert into &TRANSFORMPV_USER..E2B_CMN_ERROR_MESSAGES
   (ERROR_NUMBER, ERROR_MESSAGE, ENABLED)
 Values
   (20003, 'Cannot complete operation. Admin rights of your account have been revoked. Please contact system administrator.', 1);
Insert into &TRANSFORMPV_USER..E2B_CMN_ERROR_MESSAGES
   (ERROR_NUMBER, ERROR_MESSAGE, ENABLED)
 Values
   (20004, 'You cannot delete record(s) as child elements exists!.', 1);
Insert into &TRANSFORMPV_USER..E2B_CMN_ERROR_MESSAGES
   (ERROR_NUMBER, ERROR_MESSAGE, ENABLED)
 Values
   (20005, 'Logged-in user can not be deleted!', 1);
